language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

os:
  - linux

install:
  - pip3 install pylint pytest-cov
  - python3 setup.py install

script:
  - echo hi | ct
  - pylint chromaterm/ tests/
  - pytest --cov chromaterm/ --cov tests/ --cov-report term-missing
